### ISSUE TITLE
Database vulnerability

### ISSUE THREAD

**Issue by jjmasse** [Nisarg1792/21fahrenheit#1]
Hey there,

I am just stopping by to let you know that [connect.php](https://github.com/Nisarg1792/21fahrenheit/blob/master/connection.php) exposes your database name, username and password.

**Comment by Nisarg1792** [comment]
Hi John 

Thank you for letting me know. I will fix it this issue.  This project was fun purpose in 2013. 
I really appreciated your affort. 

Moreover, I am really interested to work with Priceline.com. 
Thank You.

**Comment by thedappernisarg** [comment]
Hi John

Thank you for letting me know. I removed file. This project was fun purpose in 2013. 
I really appreciated your affort.

Moreover, I am really interested to work with Priceline.com. 
Thank You.
